# Ensemble Technique

## These models can be used both for regression and classification 

1. Random Forest # here base estimator is dtc -{so Homogenious Model} #estimator_DecisionTreeClassifier
2. Extra Trees

## For Boosting 

1. Ada Boost 
2. Gradient Boost 
3. Xgboost

--------
**NOTE: They are Homogenious Model**

----------------

# Random Forest Classifier

**sklearn.ensemble.RandomForestClassifier**(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)

**Extra Trees** : Used where datset is very big datasets 

1. n_estimators: number of Trees to be created

In [1]:
# Import lib
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier

import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import load_iris

ds=load_iris()
ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
ds.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
df=pd.DataFrame(data=ds.data,columns=ds.feature_names)
df['target']=ds.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=20,random_state=42)

## Ensemble Technique (Bagging)

In [7]:
# RANDOM FOREST CLASSIFIER

rf=RandomForestClassifier(n_estimators=100,random_state=43)
rf.fit(train_x,train_y)
print("Training Score: ",rf.score(train_x,train_y))
pred_rf=rf.predict(test_x)

print("Accuracy Score",accuracy_score(test_y,pred_rf))
print("\nClassification Report: ",classification_report(test_y,pred_rf))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_rf))

Training Score:  1.0
Accuracy Score 1.0

Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Confusion_Matrix:
 [[6 0 0]
 [0 9 0]
 [0 0 5]]


## Bagging Model (Extra Trees Classifier)

In [8]:
# EXTRA TREES CLASSIFIER

et=ExtraTreesClassifier(n_estimators=100, random_state=43)
et.fit(train_x,train_y)
print("TRaining Score: ",et.score(train_x,train_y))
pred_et=et.predict(test_x)

# print metrics

print("Accuracy Score",accuracy_score(test_y,pred_et))
print("\nClassification Report: ",classification_report(test_y,pred_et))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_et))

TRaining Score:  1.0
Accuracy Score 1.0

Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Confusion_Matrix:
 [[6 0 0]
 [0 9 0]
 [0 0 5]]


## Boosting (Ada Boost)

In [9]:
ada=AdaBoostClassifier(n_estimators=50)
ada.fit(train_x,train_y)
print("Training Score: ",ada.score(train_x,train_y))
pred_ada=ada.predict(test_x)
print("Mertics")

print("Testing Accuracy Score",accuracy_score(test_y,pred_ada))
print("\nClassification Report: ",classification_report(test_y,pred_ada))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_ada))

Training Score:  0.9538461538461539
Mertics
Testing Accuracy Score 1.0

Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Confusion_Matrix:
 [[6 0 0]
 [0 9 0]
 [0 0 5]]


# We can check if the SVC works as the base estimiter

### Try 1

In [10]:
from sklearn.svm import SVC
svc=SVC()# on default parameter its working worse

# create ada boost classifier object
ada=AdaBoostClassifier(base_estimator=svc,algorithm='SAMME')# By default it is SAMME.R 
ada.fit(train_x,train_y)
print("Training Score: ",ada.score(train_x,train_y))
pred_ada=ada.predict(test_x)
print("Mertics")

print("Testing Accuracy Score",accuracy_score(test_y,pred_ada))
print("\nClassification Report: ",classification_report(test_y,pred_ada))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_ada))

Training Score:  0.34615384615384615
Mertics
Testing Accuracy Score 0.25

Classification Report:                precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.00      0.00      0.00         9
           2       0.25      1.00      0.40         5

    accuracy                           0.25        20
   macro avg       0.08      0.33      0.13        20
weighted avg       0.06      0.25      0.10        20


Confusion_Matrix:
 [[0 0 6]
 [0 0 9]
 [0 0 5]]


In [11]:
from sklearn.svm import SVC
svc=SVC(probability=True,kernel='poly') # in changes model is working well

# create ada boost classifier object
ada=AdaBoostClassifier(base_estimator=svc,algorithm='SAMME')# By default it is SAMME.R 
ada.fit(train_x,train_y)
print("Training Score: ",ada.score(train_x,train_y))
pred_ada=ada.predict(test_x)
print("Mertics")

print("Testing Accuracy Score",accuracy_score(test_y,pred_ada))
print("\nClassification Report:\n",classification_report(test_y,pred_ada))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_ada))

Training Score:  0.9230769230769231
Mertics
Testing Accuracy Score 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Confusion_Matrix:
 [[6 0 0]
 [0 9 0]
 [0 0 5]]


In [12]:
from sklearn.ensemble import GradientBoostingClassifier

gb=GradientBoostingClassifier()
gb.fit(train_x,train_y)
print("Training Score: ",gb.score(train_x,train_y))
pred_gb=gb.predict(test_x)
print("Mertics")

print("Testing Accuracy Score",accuracy_score(test_y,pred_gb))
print("\nClassification Report:\n",classification_report(test_y,pred_gb))
print("\nConfusion_Matrix:\n",confusion_matrix(test_y,pred_gb))

Training Score:  1.0
Mertics
Testing Accuracy Score 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20


Confusion_Matrix:
 [[6 0 0]
 [0 9 0]
 [0 0 5]]


# Voting Classifer:(Hetrogenious)



### Two Type:

#### Hard Voting
#### Soft Voting


In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB



from sklearn.ensemble import VotingClassifier

estimator=[]
estimator.append(('LR',KNeighborsClassifier()))
estimator.append(('SVC',SVC()))
estimator.append(('DTC',DecisionTreeClassifier()))
# lets see estimator
estimator

[('LR', KNeighborsClassifier()),
 ('SVC', SVC()),
 ('DTC', DecisionTreeClassifier())]

## Hard Voting is based on Votes

In [24]:
estimator=[]
estimator.append(('LR',KNeighborsClassifier()))
estimator.append(('SVC',SVC(probability=True)))
estimator.append(('DTC',DecisionTreeClassifier()))
# lets see estimator
estimator

vc_hard=VotingClassifier(estimators=estimator,voting="hard")
vc_hard.fit(train_x,train_y)
print("Score: ",vc_hard.score(train_x,train_y))
pred_y=vc_hard.predict(test_x)
print(pred_y)
print("Acc:",accuracy_score(test_y,pred_y))
print("Con\n",confusion_matrix(test_y,pred_y))
print("Classification_Report\n",classification_report(test_y,pred_y))

Score:  0.9769230769230769
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2]
Acc: 1.0
Con
 [[6 0 0]
 [0 9 0]
 [0 0 5]]
Classification_Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



##  Soft voting (IT is Based on probability)

In [27]:
vc_soft=VotingClassifier(estimators=estimator,voting="soft")
vc_soft.fit(train_x,train_y)
print("Score ",vc_soft.score(train_x,train_y))
pred_vc=vc_soft.predict(test_x)

print("Accuracy: ",accuracy_score(test_y,pred_vc))
print("classification report\n",classification_report(test_y,pred_vc))
print("Confusion_matrix\n ",confusion_matrix(test_y,pred_vc))

Score  0.9923076923076923
Accuracy:  1.0
classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Confusion_matrix
  [[6 0 0]
 [0 9 0]
 [0 0 5]]
